replicaCount: 1
image:
  repository: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/api-app
  pullPolicy: Always
  tag: "latest"
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
postgresql:
  host: postgres
  port: 5432
  database: votingdb
  user: postgres
